export enum ROUTES {
  LOGIN = "login",
  REGISTER = "register",
  FORGOT_PASSWORD = "forgot-password",
  VERIFY_ACCOUNT = "verify-account",
  ONBOARDING = "onboarding",
  ONBOARDING_LAWYER = "onboarding-lawyer",
  ONBOARDING_CUSTOMER = "onboarding-customer",
  DASHBOARD = "dashboard",
  COMMUNITIES = "community",
  COMMUNITY = ":id",
  POSTS = "posts",
  CREATE_POST = `${ROUTES.POSTS}/create`,
  POST = `${ROUTES.POSTS}/:id`,
  CALENDAR = "calendar",
  CHATS = "chats",
  CASES = "casos",
}
