export enum ROUTES {
  LOGIN = "login",
  REGISTER = "register",
  FORGOT_PASSWORD = "forgot-password",
  VERIFY_ACCOUNT = "verify-account",
  ONBOARDING = "onboarding",
  ONBOARDING_LAWYER = "onboarding-lawyer",
  ONBOARDING_CUSTOMER = "onboarding-customer",
  DASHBOARD = "dashboard",
  COMMUNITY = "community",
  CREATE_POST = "create-post",
  CALENDAR = "calendar",
  CHATS = "chats",
  CASES = "casos",
}
